# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 25c4cbbd1de51e0aae3f3e5ca8a224d3250d60e18a521f3a6bd2679e2fe1e52805155edf2a043d9d6fbe6a9d9c0eccbf8a78dfa8652882eca017499ae99d4775

test:
  secret_key_base: 8c37f4eb43d9837fc5fd4a4581651d295458ff3403ce9e91c1319b1a2c717eb06830c873012a6364e6ab1824f7c550cef3c41008bff58df4c7dd03a78844ef84

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
